services:
  - type: web
    name: telegram-bot-api
    env: docker
    region: virginia
    plan: pro
    healthCheckPath: /
    disk:
      name: telegram-bot-api-data
      mountPath: /app/data
      sizeGB: 10
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_API_PORT
        value: "8081"
      - key: WEB_PORT
        value: "8080"
